name: flutter_shop
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.5
  shared_preferences: 0.5.3+4
  event_bus: ^1.1.0
  barcode_scan: ^1.0.0
  http: ^0.12.0
  dio: 2.1.3
      # 弹吐司
      # fluttertoast: 2.2.2
    # image_picker: 0.4.12+1
    # image_picker_saver: 0.1.0
  device_info: ^0.4.0
    # loading
  flutter_spinkit: ^3.1.0
    # 上拉加载下拉刷新
  flutter_easyrefresh: 1.1.1
    # 判断网络连接
  connectivity: 0.4.3
    # 轮播图
  flutter_swiper: 1.1.6
    # 瀑布流
  flutter_staggered_grid_view: 0.3.0
    # 手机目录
  path_provider: 1.2.0
    # sqlite数据库
  sqflite: 1.1.6
  package_info: 0.4.0+6
    # 左划删除菜单
  flutter_slidable: 0.5.3
  jpush_flutter: 0.0.13
  photo_view: ^0.4.2
  json_serializable: ^3.1.0
    # 打电话发短信等
  url_launcher: 5.1.2
    # html
  flutter_html: 0.10.4
  fluttertoast: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    # image_picker:
    # path: image_picker
  native_plugin:
    path: native_plugin
    # 这两个是dev的，不要放到上面去了哦
  build_runner: 1.6.5


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/bg.jpeg
    - images/bg1.jpg
    - images/bg2.jpg
    - images/home.png
    - images/home_selected.png
    - images/category.png
    - images/category_selected.png
    - images/want.png
    - images/want_selected.png
    - images/cart.png
    - images/cart_selected.png
    - images/mine.png
    - images/mine_selected.png
    - images/cusomer_service.png
    - images/icon_qq.png
    - images/icon_wechat.png
    - images/icon_search.png
    - images/search_search.png
    - images/notice.png
    - images/clock.png
    - images/time_selected_bg.png
    - images/share.png
    - images/filter.png
    - images/icon_delete.png
    - images/icon_clear.png
    - images/icon_fire.png
    - images/icon_global_price.png
    - images/icon_unit_price.png
    - images/collect.png
    - images/collect_pressed.png
    - images/logistics_order.png
    - images/logistics_sure.png
    - images/logistics_cart.png
    - images/logistics_air.png
    - images/logistics_location.png
    - images/mine_bg.png
    - images/headimg.png
    - images/icon_browse.png
    - images/icon_collect.png
    - images/customer_service.png
    - images/account.png
    - images/login_bg.png
    - images/login_logo.png
    - images/password.png
    - images/pwd_close.png
    - images/pwd_open.png
    - images/order_to_be_pay.png
    - images/order_not_deliver.png
    - images/order_not_take.png
    - images/order_all.png
    - images/order_return.png
    - images/account_center_supplier.png
    - images/good_stock_bg.png
    - images/default_good_image.png


    - datas/recommends.json
    - datas/message.json
    - datas/mytracks.json
    - datas/message_details.json
    - datas/my_want.json
    - datas/category.json
    - datas/goodsdetail.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
